import Head from 'next/head'
import Link from 'next/link'
import { me } from '../../data/me'

function Blog() {
  return (
    <div>
      <Head>
        <title>Blog | {`${me.middlename} ${me.lastname}`}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h2 className='px-8 py-3 my-3 border border-transparent text-base font-bold bg-indigo-100 rounded-md md:py-4 md:text-lg md:px-10'>
          All Posts
        </h2>
      </main>
    </div>
  )
}

export default Blog
