import Head from 'next/head'
import { me } from '../data/me'

export default function Home() {
  return (
    <div>
      <Head>
        <title>About | {`${me.middlename} ${me.lastname}`}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h2 className='text-xl font-bold uppercase'>Hey, Nice to meet u!</h2>
        <p className='text-gray-600 mt-4'>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Te enim
          iudicem aequum puto, modo quae dicat ille bene noris. At iste non
          dolendi status non vocatur voluptas. Nam memini etiam quae nolo,
          oblivisci non possum quae volo. Duo Reges: constructio interrete.
        </p>

        <h2 className='text-xl font-bold uppercase mt-4'>Welcome!</h2>
        <p className='text-gray-600 mt-4'>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Te enim
          iudicem aequum puto, modo quae dicat ille bene noris. At iste non
          dolendi status non vocatur voluptas. Nam memini etiam quae nolo,
          oblivisci non possum quae volo. Duo Reges: constructio interrete.
        </p>
      </main>
    </div>
  )
}
